version: "3.7"

services:
  www:
    container_name: apache
#    build: ./front-end/
    image: httpd:2.4-alpine
    networks:
      - front-end
    ports:
      - 8081:80
    env_file:
      - .env.dev
    depends_on:
      - back-api
    volumes:
      - ./front-end/:/usr/local/apache2/front-end/
      - ./front-end/dist:/usr/local/apache2/htdocs/

  back-api:
    container_name: php-api
    build: ./back-end/
    image: back-end:latest
    networks:
      - front-end
      - back-end
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env.dev
    volumes:
      - ./back-end:/app
    command: php -S 0.0.0.0:8000

  db:
    container_name: mysql
    image: mysql:8.0
    build: ./db
    networks:
      - back-end
    env_file:
      - .env.dev
    ports:
      - 3306
    command: --default-authentication-plugin=mysql_native_password

networks:
 front-end:
 back-end: