CREATE DATABASE MEDIALIBRARY;

USE MEDIALIBRARY;

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(63) NOT NULL,
    password VARCHAR(63) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FILES (
    owner_ID INT NOT NULL,
    name VARCHAR(63) NOT NULL,
    URL VARCHAR(63) NOT NULL,
    thumbnail_URL VARCHAR(63),
    type VARCHAR(63) NOT NULL,
    ID VARCHAR(63) NOT NULL UNIQUE,
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)