CREATE DATABASE MEDIALIBRARY;

USE MEDIALIBRARY;

CREATE TABLE USERS (
    user_ID INT AUTO_INCREMENT NOT NULL,
    user_name VARCHAR(63) NOT NULL,
    user_password VARCHAR(63) NOT NULL,
    PRIMARY KEY (user_ID)
);

CREATE TABLE FILES (
    file_owner VARCHAR(63) NOT NULL,
    file_name VARCHAR(63) NOT NULL,
    file_URL VARCHAR(63) NOT NULL,
    file_thumbnail_URL VARCHAR(63),
    file_type VARCHAR(63) NOT NULL,
    file_ID VARCHAR(63) NOT NULL UNIQUE,
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)